/**
 * Feature: CRM Deals Workspace — Settings tab
 *
 * Scenarios covered:
 *   @p1   Dynamic ID fields regenerate on every render
 *   @p1   Dynamic fields are targetable by label when IDs change
 *   @p0   Delete confirmation button is disabled for 3 seconds
 *   @p0   Confirming deletion clears all app data
 *   @p1   Cancelling the delete modal restores normal state
 *
 * Testing challenges addressed:
 *   - Dynamic IDs: reRenderDynamicFields() stamps new IDs on every call.
 *     The Settings tab triggers reRenderDynamicFields() on every tab switch.
 *     Tests target fields by getByLabel() — the label text is stable.
 *   - Timed modal: confirm button is disabled for 3 seconds. Clicking it
 *     before it enables silently does nothing. Test uses toBeEnabled() with
 *     an explicit timeout — NOT a fixed waitForTimeout(3000).
 */

import { test, expect, switchTab, openDeleteModalAndWaitForCountdown, fillContactForm, saveContact } from './crm.fixtures';

test.describe('Settings tab @crm', () => {
  test.use({ storageState: undefined });

  test.beforeEach(async ({ crmPage: page }) => {
    await switchTab(page, 'Settings');
  });

  // ─── @p1 ──────────────────────────────────────────────────────────────────
  test('[P1] Dynamic ID fields regenerate on every render', async ({ crmPage: page }) => {
    await test.step('Record current IDs of the three dynamic inputs', async () => {
      // IDs are already generated by the initial tab switch
    });

    const idsBefore = await page.locator('#dynamic-fields input').evaluateAll(
      (els: HTMLInputElement[]) => els.map((e) => e.id)
    );

    await test.step('Click "Re-render fields"', async () => {
      await page.getByRole('button', { name: 'Re-render fields' }).click();
    });

    const idsAfter = await page.locator('#dynamic-fields input').evaluateAll(
      (els: HTMLInputElement[]) => els.map((e) => e.id)
    );

    await test.step('All three IDs are different from before', async () => {
      expect(idsAfter).toHaveLength(3);
      for (let i = 0; i < 3; i++) {
        expect(idsAfter[i], `Input ${i} ID should change after re-render`).not.toBe(idsBefore[i]);
      }
    });
  });

  // ─── @p1 ──────────────────────────────────────────────────────────────────
  test('[P1] Dynamic fields are targetable by label when IDs change', async ({ crmPage: page }) => {
    await test.step('Click "Re-render fields" to force new IDs', async () => {
      await page.getByRole('button', { name: 'Re-render fields' }).click();
    });

    await test.step('Fill "Config key" using its label locator', async () => {
      await page.getByLabel('Config key').fill('my-config-key');
      await expect(page.getByLabel('Config key')).toHaveValue('my-config-key');
    });

    await test.step('Fill "Webhook URL" using its label locator', async () => {
      await page.getByLabel('Webhook URL').fill('https://example.com/webhook');
      await expect(page.getByLabel('Webhook URL')).toHaveValue('https://example.com/webhook');
    });

    await test.step('Fill "API token" using its label locator', async () => {
      await page.getByLabel('API token').fill('tok-abc123');
      await expect(page.getByLabel('API token')).toHaveValue('tok-abc123');
    });
  });

  // ─── @p0 ──────────────────────────────────────────────────────────────────
  test('[P0] Delete confirmation button is disabled for 3 seconds', async ({ crmPage: page }) => {
    await test.step('Click "Delete account"', async () => {
      await page.locator('#open-delete-btn').click();
    });

    await test.step('Confirmation modal appears', async () => {
      await expect(page.locator('#delete-modal-wrap')).toBeVisible();
    });

    await test.step('"Delete" button is disabled immediately', async () => {
      await expect(page.locator('#confirm-delete-btn')).toBeDisabled();
    });

    await test.step('Countdown text reads "Button enables in 3s…"', async () => {
      await expect(page.locator('#modal-countdown')).toHaveText('Button enables in 3s…');
    });

    await test.step('After countdown completes, "Delete" button becomes enabled', async () => {
      // toBeEnabled() with 5s timeout waits for the natural countdown — no hard sleep needed
      await expect(page.locator('#confirm-delete-btn')).toBeEnabled({ timeout: 5_000 });
    });

    await test.step('Countdown text reads "You may now confirm."', async () => {
      await expect(page.locator('#modal-countdown')).toHaveText('You may now confirm.');
    });

    // Cleanup: close modal so other tests are not affected
    await page.getByRole('button', { name: 'Cancel' }).click();
  });

  // ─── @p0 ──────────────────────────────────────────────────────────────────
  test('[P0] Confirming deletion clears all app data', async ({ crmPage: page }) => {
    await test.step('Seed at least 1 deal (already present from initial load)', async () => {
      await switchTab(page, 'Deals');
      await expect(page.locator('#deals-body tr[data-deal-id]')).not.toHaveCount(0);
    });

    await test.step('Seed at least 1 contact', async () => {
      await switchTab(page, 'Contacts');
      await fillContactForm(page, { fname: 'Seed', lname: 'Contact', dept: 'Marketing' });
      await saveContact(page);
      await expect(page.locator('#contacts-body tr[data-contact-id]')).not.toHaveCount(0);
    });

    await switchTab(page, 'Settings');

    await test.step('Open delete modal and wait for confirm button to enable', async () => {
      await openDeleteModalAndWaitForCountdown(page);
    });

    await test.step('Click "Delete"', async () => {
      await page.locator('#confirm-delete-btn').click();
    });

    await test.step('Deals table shows "No deals"', async () => {
      await switchTab(page, 'Deals');
      await expect(page.locator('#deals-body')).toContainText('No deals');
    });

    await test.step('Contacts table shows "No contacts yet"', async () => {
      await switchTab(page, 'Contacts');
      await expect(page.locator('#contacts-body')).toContainText('No contacts yet');
    });

    await test.step('Pipeline total shows "$0" and avg shows "0%"', async () => {
      await switchTab(page, 'Pipeline');
      await expect(page.locator('#pipeline-total')).toHaveText('$0');
      await expect(page.locator('#pipeline-avg')).toHaveText('0%');
    });

    await test.step('Notification count shows "0"', async () => {
      await expect(page.locator('#notif-count')).toHaveText('0');
    });
  });

  // ─── @p1 ──────────────────────────────────────────────────────────────────
  test('[P1] Cancelling the delete modal restores normal state', async ({ crmPage: page }) => {
    // Record deal count before modal opens
    await switchTab(page, 'Deals');
    const dealCountBefore = await page.locator('#deals-body tr[data-deal-id]').count();
    await switchTab(page, 'Settings');

    await test.step('Open the delete modal', async () => {
      await page.locator('#open-delete-btn').click();
      await expect(page.locator('#delete-modal-wrap')).toBeVisible();
    });

    await test.step('Click "Cancel"', async () => {
      await page.getByRole('button', { name: 'Cancel' }).click();
    });

    await test.step('Modal closes', async () => {
      await expect(page.locator('#delete-modal-wrap')).toBeHidden();
    });

    await test.step('Deals data remains unchanged', async () => {
      await switchTab(page, 'Deals');
      await expect(page.locator('#deals-body tr[data-deal-id]')).toHaveCount(dealCountBefore);
    });
  });
});
